name: Build Dev Docker image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DockerUser }}   
        DOCKER_PASSWORD: ${{ secrets.DockerPassword }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . --file ./Docker/nodered-dev/Dockerfile --tag breiti78/mynodered:dev
    - name: docker push
      run: |
        docker push breiti78/mynodered:dev  
    - name: Telegram sender
      uses: robotomize/notify-telegram@v0.2.4
      with:
        # Chat to send: chat id or @channel_name
        chat: ${{ secrets.TELEGRAMCHATID }}
        # Telegram Bot token
        token: ${{ secrets.TELEGRAMTOKEN }}
        # Job status
        status: ${{ job.status }}
        message: "Docker Dev Image successfully build" # custom messag
